### ISSUE TITLE
Add a documentation flavour

### ISSUE THREAD

**Issue by atamanroman** [adorsys-containers/ci-build#4]
Pretty much every project creates some sort of documentation. Tools often include

- asciidoctor (needs Ruby)
- plantuml (needs Java)
- some sort of PDF generator (needs nodejs/chrome-headless)
- make

This results in a pretty big image. Is a specialized _documentation_ image in scope? Or part of the full image? Or completely not in scope for ci-build?

Right now we're using this one:
https://github.com/adorsys-containers/arc42-tools/blob/master/Dockerfile

**Comment by jkroepke** [comment]
> Or completely not in scope for ci-build?

Yes.

For this case we have arc42-tools like you described. Isn't this good enough? Any caveats?
